-- MySQL Script generated by MySQL Workbench
-- Tue Aug  8 11:36:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Culo-E-Botella
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Culo-E-Botella` ;
USE `Culo-E-Botella` ;

-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`addresses` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`addresses` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(45) NULL,
  `door` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`suppliers` (
  `NIF` VARCHAR(9) NULL,
  `name` VARCHAR(95) NOT NULL,
  `id_address` INT UNSIGNED NOT NULL COMMENT 'Se vincula con un id de la tabla direcciones.',
  `telephone` INT NOT NULL,
  `fax` INT NOT NULL,
  PRIMARY KEY (`NIF`, `id_address`),
  INDEX `ngf_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_address`
    FOREIGN KEY (`id_address`)
    REFERENCES `Culo-E-Botella`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`persons` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`persons` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_address` INT UNSIGNED NOT NULL COMMENT 'It\'s linked to the same table that supliers are',
  `telephone` INT NOT NULL,
  `e-mail` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `id_address`),
  INDEX `fkDirección_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_address`
    FOREIGN KEY (`id_address`)
    REFERENCES `Culo-E-Botella`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Almaceno toda la información genérica de una persona';


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`brands` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`brands` (
  `id_brand` INT NULL AUTO_INCREMENT COMMENT 'Podría presindirse pero lo dejo para hacer más fácil la búsqueda',
  `brand` VARCHAR(45) NOT NULL,
  `id_supplier` VARCHAR(9) NOT NULL COMMENT ' Es varchar para coincidir con el NIF, que es el pk de proveedor',
  PRIMARY KEY (`id_brand`),
  INDEX `fkProveedor_idx` (`id_supplier` ASC) VISIBLE,
  CONSTRAINT `fk_supplier`
    FOREIGN KEY (`id_supplier`)
    REFERENCES `Culo-E-Botella`.`suppliers` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabla para generar las relaciones exigidas por el ejercicio.';


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`lens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`lens` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`lens` (
  `id_lens` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  `graduation` FLOAT NULL,
  PRIMARY KEY (`id_lens`))
ENGINE = InnoDB
COMMENT = 'Cada fila es una combinación de color y graduación para un lente.';


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`lens_combination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`lens_combination` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`lens_combination` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `id_left_lens` INT UNSIGNED NOT NULL,
  `id_right_lens` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_left_lens`, `id_right_lens`),
  INDEX `fk_lenteIzq_idx` (`id_left_lens` ASC, `id_right_lens` ASC) VISIBLE,
  CONSTRAINT `fk_lens`
    FOREIGN KEY (`id_left_lens` , `id_right_lens`)
    REFERENCES `Culo-E-Botella`.`lens` (`id_lens` , `id_lens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'En cada fila tiene una combinación de las características del lente izq y el derecho, vinculados con su id proveniente de la tabla Lentes';


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`frames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`frames` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`frames` (
  `id` INT UNSIGNED NULL,
  `frame_type` ENUM('pasta', 'flotante', 'metal') NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`glasses` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`glasses` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `id_brand` INT UNSIGNED NOT NULL,
  `id_frame` INT UNSIGNED NOT NULL,
  `price` FLOAT NOT NULL,
  `id_conbination` INT UNSIGNED NOT NULL COMMENT 'Links with lens_combinations, with info of each glass from lens table',
  PRIMARY KEY (`id`, `price`, `id_brand`, `id_conbination`, `id_frame`),
  UNIQUE INDEX `marca_UNIQUE` (`id_brand` ASC) VISIBLE,
  INDEX `fkCombinación_idx` (`id_conbination` ASC) VISIBLE,
  INDEX `fk_frames_idx` (`id_frame` ASC) VISIBLE,
  CONSTRAINT `fk_brands`
    FOREIGN KEY (`id_brand`)
    REFERENCES `Culo-E-Botella`.`brands` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combination`
    FOREIGN KEY (`id_conbination`)
    REFERENCES `Culo-E-Botella`.`lens_combination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frames`
    FOREIGN KEY (`id_frame`)
    REFERENCES `Culo-E-Botella`.`frames` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`clients` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`clients` (
  `id` INT UNSIGNED NOT NULL,
  `id_referred` INT UNSIGNED NULL,
  `registered_date` DATE NOT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  INDEX `fkReferido_idx` (`id_referred` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_person_idx` (`id_person` ASC) VISIBLE,
  CONSTRAINT `fk_person`
    FOREIGN KEY (`id_person`)
    REFERENCES `Culo-E-Botella`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referred`
    FOREIGN KEY (`id_referred`)
    REFERENCES `Culo-E-Botella`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Datos específicos de los clientes como el referido y la fecha de registro.';


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`orders` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_seller` INT UNSIGNED NOT NULL,
  `id_client` INT UNSIGNED NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fkVendedor_idx` (`id_seller` ASC) VISIBLE,
  INDEX `fkCliente_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_seller`
    FOREIGN KEY (`id_seller`)
    REFERENCES `Culo-E-Botella`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `Culo-E-Botella`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Relaciona en cada transacción qué gafa con qué vendedor qué cliente y en qué momento';


-- -----------------------------------------------------
-- Table `Culo-E-Botella`.`glasses_in_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Culo-E-Botella`.`glasses_in_order` ;

CREATE TABLE IF NOT EXISTS `Culo-E-Botella`.`glasses_in_order` (
  `id_glasses` INT UNSIGNED NULL,
  `id_orders` INT UNSIGNED NULL,
  `glasses_quantity` INT UNSIGNED NOT NULL,
  INDEX `fk_orders_idx` (`id_orders` ASC) VISIBLE,
  PRIMARY KEY (`id_orders`, `id_glasses`),
  INDEX `fk_glasses_idx` (`id_glasses` ASC) VISIBLE,
  CONSTRAINT `fk_orders`
    FOREIGN KEY (`id_orders`)
    REFERENCES `Culo-E-Botella`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses`
    FOREIGN KEY (`id_glasses`)
    REFERENCES `Culo-E-Botella`.`glasses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
